### PR TITLE
[Major] Updated to Maven project

### PR DESCRIPTION
**Pull request by eitch**
I updated the project and also changed the ports from 123 to something else, so it runs on my linux system (ports below 1024 require root privileges).

### CODE REVIEW

**Comment by PvdBerg1998** [comment]
Maven is actually really nice, thank you. Is there a way to get rid of the 'main' in front of every package in the jar release?

**Comment by eitch** [comment]
Now that you have merged my PR, you can simply refactor the packages to be without the main. This was already like that, which is why i didn't change it.

**Comment by PvdBerg1998** [comment]
Must've forgotten to push. I'm changing a few things in the pom.xml before publishing to Maven Central.

**Comment by eitch** [comment]
If you need any pointers on how to push to Maven Central, then you can check this project on what the POM must look like: https://github.com/eitch/ch.eitchnet.beaglebone

You'll also need to change the groupId to be a reverse domain name which you own.

**Comment by PvdBerg1998** [comment]
> which you own

Is this required? Can't I just use `nl.pvdberg.pnet`?

**Comment by eitch** [comment]
I think you have to own it, but you have to create a Jira ticket for the groupId first anyhow: http://www.sonatype.org/nexus/2015/01/08/deploy-to-maven-central-repository/ See point 1.

**Pull request merged**
